# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-20 19:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 20, 21, 53, 33, 272989)),
        ),
    ]
